### ISSUE TITLE
Vmesno poročilo

### ISSUE THREAD

**Issue by matijapretnar** [urska19/MFP---Samodejno-racunanje-dvosmernih-preslikav#1]
Ali lahko prosim na kratko napišeta, kaj sta že naredili in kaj še mislita? S profesorjem sva razmišljala, da je projekt zahtevnejši, zato bo optimizacija, opisana v članku, načeloma že dovolj za 10.

**Comment by urska19** [comment]
Do zdaj imava osnovno verzijo skoraj končano (manjka še module zippable). Nisva se še odločili, če bova naredili še kaj več; ampak, če se odločiva za to, potem sva mislili poskusiti implementirati optimizacijo iz članka.

V kratkem se bova še oglasili pri profesorju, da poročava kako nama kaj gre.
